### ISSUE TITLE
Add docs for setup and testing

### ISSUE THREAD

**Issue by rtnpro** [tmrts/flamingo#1]
It'd be great if there are docs to:
- setup
- use
- test
  flamingo.

It could be as simple as the quickstart for cloud-init at http://www.projectatomic.io/docs/quickstart/

**Comment by tmrts** [comment]
I've provided documentation for the tasks you've listed as well as script binaries to test/build/install flamingo. You can also get the binary built for fedora from [v0.1.0](https://github.com/tmrts/flamingo/releases/tag/v0.1.0). Let me know if you have any issues.
